export const dummy = [
  [
    {
      postId: 1,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_0.jpeg`,
      postLikeCounts: 1,
      commentCounts: 12135,
      nuKcal: 1023,
    },
    {
      postId: 424,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_1.jpeg`,
      postLikeCounts: 2,
      commentCounts: 2,
      nuKcal: 134,
    },
    {
      postId: 52,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_2.jpeg`,
      postLikeCounts: 3,
      commentCounts: 3,
      nuKcal: 4535,
    },
    {
      postId: 74,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_3.jpeg`,
      postLikeCounts: 4,
      commentCounts: 4254,
      nuKcal: 4545,
    },
    {
      postId: 55,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_4.jpeg`,
      postLikeCounts: 5,
      commentCounts: 58882,
      nuKcal: 543,
    },
  ],
  [
    {
      postId: 1224,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_5.jpeg`,
      postLikeCounts: 64507,
      commentCounts: 6,
      nuKcal: 2123,
    },
    {
      postId: 4443,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_6.jpeg`,
      postLikeCounts: 7,
      commentCounts: 7000,
      nuKcal: 444,
    },
    {
      postId: 10,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_7.jpeg`,
      postLikeCounts: 35000,
      commentCounts: 8,
      nuKcal: 868,
    },
    {
      postId: 789,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_8.jpeg`,
      postLikeCounts: 9,
      commentCounts: 9,
      nuKcal: 189,
    },
    {
      postId: 523,
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_9.jpeg`,
      postLikeCounts: 10,
      commentCounts: 20000,
      nuKcal: 3421,
    },
  ],
];
