export const dummy = [
  [
    {
      postId: "test1",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_0.jpeg`,
      postLikeCounts: "좋아요 수 1",
      commentCounts: "댓글 수 1",
      mealCount: "식사수 1",
      nuKcal: "1023칼로리",
    },
    {
      postId: "test2",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_1.jpeg`,
      postLikeCounts: "좋아요 수2",
      commentCounts: "댓글 수 2",
      mealCount: "식사수 2",
      nuKcal: "134칼로리",
    },
    {
      postId: "test3",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_2.jpeg`,
      postLikeCounts: "좋아요 수 3",
      commentCounts: "댓글 수 3",
      mealCount: "식사수 3",
      nuKcal: "4535칼로리",
    },
    {
      postId: "test4",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_3.jpeg`,
      postLikeCounts: "좋아요 수 4",
      commentCounts: "댓글 수 4",
      mealCount: "식사수4",
      nuKcal: "4545칼로리",
    },
    {
      postId: "test5",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_4.jpeg`,
      postLikeCounts: "좋아요 수 5",
      commentCounts: "댓글 수 5",
      mealCount: "식사수 5",
      nuKcal: "543칼로리",
    },
  ],
  [
    {
      postId: "test6",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_5.jpeg`,
      postLikeCounts: "좋아요 수 6",
      commentCounts: "댓글 수 6",
      mealCount: "식사수 6",
      nuKcal: "2123칼로리",
    },
    {
      postId: "test7",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_6.jpeg`,
      postLikeCounts: "좋아요 수 7",
      commentCounts: "댓글 수 7",
      mealCount: "식사수 7",
      nuKcal: "444칼로리",
    },
    {
      postId: "test8",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_7.jpeg`,
      postLikeCounts: "좋아요 수 8",
      commentCounts: "댓글 수 8",
      mealCount: "식사수 8",
      nuKcal: "868칼로리",
    },
    {
      postId: "test9",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_8.jpeg`,
      postLikeCounts: "좋아요 수 9",
      commentCounts: "댓글 수 9",
      mealCount: "식사수 9",
      nuKcal: "189칼로리",
    },
    {
      postId: "test10",
      postImageUrls: `${process.env.PUBLIC_URL}/assets/main/main_food_9.jpeg`,
      postLikeCounts: "좋아요 수 10",
      commentCounts: "댓글 수 10",
      mealCount: "식사수 10",
      nuKcal: "3421칼로리",
    },
  ],
];
